---
title: "Ocean interior storage"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r load_library}
library(ggnewscale)
library(scales)
library(gtable)
library(grid)
library(zoo)
```


# Data

```{r set_file_path}

path_updata <- "/nfs/kryo/work/updata/"
path_emlr_preprocessing <- "/nfs/kryo/work/jenmueller/emlr_cant/observations/preprocessing/"

file_khatiwala <- paste0(path_updata,
                         "cant_khatiwala_2009/carbon_inventory_khatiwala_2009.txt")


```

## Gruber 2019

```{r read_G19}

dcant_inv_G19 <-
  read_csv(paste(path_emlr_preprocessing,
                  "G19_dcant_inv_publ.csv",
                  sep = ""))


dcant_G19 <- bind_cols(year = 2007, dcant_mean = 34, dcant_sd = 4)

```

## Sabine 2004

```{r read_S04}

tcant_inv_S04 <-
  read_csv(paste(path_emlr_preprocessing,
                  "S04_tcant_inv.csv", sep = ""))

tcant_inv_S04 <- tcant_inv_S04 %>% 
  select(-c(tcant, inv_depth, basin_AIP))

tcant_S04 <- bind_cols(year = 1994, dcant_mean = 118, dcant_sd = 19)

```

## Khatiwala

```{r read_khatiwala}

khatiwala <- read_table(file_khatiwala)

```

## GCB 2021

```{r read_GCB}

# Historical_Budget <-
#   read_csv(paste(path_emlr_preprocessing,
#                   "GCB_Historical_Budget.csv",
#                   sep = ""))

Ocean_Sink <- 
  read_csv(paste(path_emlr_preprocessing,
                  "Ocean_Sink.csv",
                  sep = ""))
```

## Atm CO2

```{r read_atm_CO2}

co2_atm_reccap2 <-
  read_csv(paste(path_emlr_preprocessing,
                  "co2_atm_reccap2.csv",
                  sep = ""))

```

## Lauvset 2016

```{r read_GLODAP_climatology, fig.asp=0.4}

variables <-
  c("PO4", "TAlk", "TCO2", "Cant")

# i_variable <- variables[1]

for (i_variable in variables) {
  temp <- read_csv(paste(
    path_emlr_preprocessing,
    paste("GLODAPv2_2016_MappedClimatology_", i_variable, ".csv", sep = ""),
    sep = ""
  ))
  
  if (exists("GLODAP_predictors")) {
    GLODAP_predictors <- full_join(GLODAP_predictors, temp)
  }
  
  if (!exists("GLODAP_predictors")) {
    GLODAP_predictors <- temp
  }
}

rm(temp, variables)


```

# Delta C gasex

## Histograms

```{r calc_delta_C_gasex}

# calculate C*
GLODAP_predictors <- GLODAP_predictors %>%
  mutate(cstar = TCO2  -
           (117 * PO4)  - 0.5 * (TAlk + (16 * PO4)))


GLODAP_predictors %>% 
  ggplot(aes(cstar)) +
  geom_histogram()

constant <- median(GLODAP_predictors$cstar, na.rm = TRUE)

GLODAP_predictors <- GLODAP_predictors %>%
  mutate(dCgasex = cstar - Cant - constant)

GLODAP_predictors %>% 
  ggplot(aes(dCgasex)) +
  geom_histogram()

GLODAP_predictors_zonal <- 
  m_zonal_mean_sd(GLODAP_predictors)

```

## Sections

### Zonal

```{r zonal_sections_delta_C_gasex}

for (i_basin_AIP in unique(GLODAP_predictors_zonal$basin_AIP)) {
  
  print(i_basin_AIP)
  
  for (i_layer in c("surface", "deep")) {
    # i_basin_AIP <- unique(GLODAP_predictors_zonal$basin_AIP)[1]
    # i_layer <- c("surface", "deep")[1]
    
    GLODAP_predictors_zonal_sub <- GLODAP_predictors_zonal %>%
      filter(basin_AIP == i_basin_AIP)
    
    p_all <- GLODAP_predictors_zonal_sub %>%
      ggplot() +
      guides(fill = guide_colorsteps(barheight = unit(8, "cm"))) +
      scale_x_continuous(
        breaks = seq(-100, 100, 20),
        limits = c(-89.5, 89.5),
        name = "Latitude [°N]"
      ) +
      geom_contour_filled(aes(lat, depth, z = dCgasex_mean),
                          breaks = c(-Inf, seq(-50, 50, 10), Inf)) +
      geom_contour(aes(lat, depth, z = Cant_mean),
                   breaks = c(seq(0, 70, 10), Inf),
                   col = "black") +
      geom_text_contour(
        aes(lat, depth, z = Cant_mean),
        breaks = c(seq(0, 70, 10), Inf),
        stroke = 0.2,
        rotate = FALSE
      ) +
      colorspace::scale_fill_discrete_diverging(
        palette = "Blue-Red",
        drop = FALSE,
        name = expression(atop(Delta ~ C["gasex"],
                               "[µmol" ~ kg ^ {
                                 -3
                               } ~ "]")),
        rev = TRUE
      )
    
    if (i_layer == "surface") {
      p_sub <- p_all +
        scale_y_reverse(breaks = seq(0, 500, 100),
                        name = "Depth [m]") +
        coord_cartesian(expand = 0, ylim = c(500, 0))
    }
    
    if (i_layer == "deep") {
      p_sub <- p_all +
        scale_y_reverse(breaks = seq(500, 5000, 1000),
                        name = "Depth [m]") +
        coord_cartesian(expand = 0, ylim = c(5000, 500))
    }
    
    print(p_sub)
    
 
    pdf(here::here(
      paste0(
        "output/Fig5_sections/Fig5_section_zonal_",
        i_basin_AIP,
        "_",
        i_layer,
        ".pdf"
      )
    ),
    width = 12,
    height = 5)
    
    print(p_sub)
    
    dev.off()
    
    
    
  }
}

rm(GLODAP_predictors_zonal,
   GLODAP_predictors_zonal_sub)

```

### Meridional Southern Ocean

```{r meriodional_SO_section_delta_C_gasex}
GLODAP_predictors_meriodional_SO <- GLODAP_predictors %>%
  filter(lat < -55,
         lat > -60) %>%
  mutate(lon = if_else(lon > 180, lon - 360, lon)) %>% 
  group_by(lon, depth) %>%
  summarise(
    dCgasex_mean = mean(dCgasex, na.rm = TRUE),
    Cant_mean = mean(Cant, na.rm = TRUE)
  ) %>%
  ungroup()

for (i_layer in c("surface", "deep")) {
  # i_layer <- c("surface", "deep")[1]
  
  
  p_all <- GLODAP_predictors_meriodional_SO %>%
    ggplot() +
    guides(fill = guide_colorsteps(barheight = unit(8, "cm"))) +
    scale_x_continuous(
      breaks = seq(-180, 180, 30),
      name = "Longitude [°E]") +
    geom_contour_filled(aes(lon, depth, z = dCgasex_mean),
                        breaks = c(-Inf, seq(-50, 50, 10), Inf)) +
    geom_contour(aes(lon, depth, z = Cant_mean),
                 breaks = c(seq(0, 70, 10), Inf),
                 col = "black") +
    geom_text_contour(
      aes(lon, depth, z = Cant_mean),
      breaks = c(seq(0, 70, 10), Inf),
      stroke = 0.2,
      # stroke.colour = "transparent",
      rotate = FALSE
    ) +
    colorspace::scale_fill_discrete_diverging(
      palette = "Blue-Red",
      drop = FALSE,
      name = expression(atop(Delta ~ C["gasex"],
                             "[µmol" ~ kg ^ {
                               -3
                             } ~ "]")),
      rev = TRUE
    )
  
  if (i_layer == "surface") {
    p_sub <- p_all +
      scale_y_reverse(breaks = seq(0, 500, 100),
                      name = "Depth [m]") +
      coord_cartesian(expand = 0, ylim = c(500, 0))
  }
  
  if (i_layer == "deep") {
    p_sub <- p_all +
      scale_y_reverse(breaks = seq(500, 5000, 1000),
                      name = "Depth [m]") +
      coord_cartesian(expand = 0, ylim = c(5000, 500))
  }
  
  print(p_sub)
  
  
  pdf(here::here(
    paste0(
      "output/Fig5_sections/Fig5_section_",
      "meridional_Southern",
      "_",
      i_layer,
      ".pdf"
    )
  ),
  width = 12,
  height = 5)
  
  print(p_sub)
  
  dev.off()
}

rm(GLODAP_predictors_meriodional_SO, p_all, p_sub)
    
```

# Cant column inventories

## Join data

```{r merge_G19_S04}

tcant_2007 <- full_join(dcant_inv_G19,
                        tcant_inv_S04)

# map data coverage
tcant_2007 <- tcant_2007 %>% 
  mutate(data_missing = if_else(is.na(dcant_pos), "G19", "available"),
         data_missing = if_else(is.na(tcant_pos), "S04", data_missing),
         data_missing = if_else(is.na(tcant_pos) & is.na(dcant_pos), "S04&G19", data_missing))

# calculate total Cant in 2007
tcant_2007 <- tcant_2007 %>% 
  mutate(tcant_pos_2007 = tcant_pos + dcant_pos)

# relative contribution of 1994 - 2007 period to total in 2007
# tcant_2007_contribution <- tcant_2007 %>% 
#   mutate(G19_contribution = 100* dcant_pos / tcant_pos_2007) %>% 
#   select(-starts_with(c("dcant", "tcant", "data")))

tcant_2007 <- tcant_2007 %>% 
  select(lon, lat, tcant_1994 = tcant_pos, dcant_1994_2007 = dcant_pos, data_missing)

```

## Maps

```{r plot_maps, fig.asp=1}

tcant_label <- expression(atop(total~C["ANT"],
                                "[mol" ~ m ^ { -2 }~"]"))

dcant_label <- expression(atop(Delta*C["ANT"],
                                "[mol" ~ m ^ { -2 }~"]"))

p_data_coverage <- map +
  geom_tile(data = tcant_2007 %>% filter(data_missing != "available"),
            aes(lon, lat, fill = data_missing)) +
  scale_fill_brewer(palette = "Set1", direction = -1) +
  new_scale("fill") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

# p_data_coverage
  
p_tcant_binned_1994 <- map +
  geom_tile(data = tcant_2007 %>% filter(!is.na(tcant_1994)),
            aes(lon, lat, fill = tcant_1994)) +
  scale_fill_binned_sequential("rocket",
                               name = tcant_label,
                               breaks = seq(0,100,10)) +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )

# p_tcant_binned_1994

p_dcant_binned_1994_2007 <- map +
  geom_tile(data = tcant_2007 %>% filter(!is.na(dcant_1994_2007)),
            aes(lon, lat, fill = dcant_1994_2007)) +
  scale_fill_binned_sequential("rocket",
                               name = dcant_label,
                               breaks = seq(0,20,2.5)) +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )

# p_dcant_binned_1994_2007

p_tcant_binned_1994 + p_dcant_binned_1994_2007 + p_data_coverage + 
  plot_layout(ncol = 1)

ggsave(here::here("output/Fig1b.jpg"),
       width = 6,
       height = 6)

# map +
#   geom_tile(data = tcant_2007_contribution %>% filter(!is.na(G19_contribution)),
#             aes(lon, lat, fill = G19_contribution)) +
#   scale_fill_binned_divergingx(palette = "RdBu",
#                                breaks = c(-Inf, seq(10, 50, 5), Inf),
#                                mid = 25)

```

## Write files

```{r write_column_inventory_files}

tcant_2007 <- tcant_2007 %>%
  mutate(lon = if_else(lon > 360, lon - 360, lon),
         tcant_1994 = round(tcant_1994, 3),
         dcant_1994_2007 = round(dcant_1994_2007, 3))

tcant_2007 %>% 
  ggplot(aes(lon, lat)) +
  geom_tile() +
  labs(title = "formatted longitudes") +
  coord_quickmap(expand = 0)

tcant_2007 %>% 
  write_csv(here::here("output/Fig1b_data.csv"))


```



# Time series

## Prepare data

### Delta C*

```{r prepare_SO4_G19}

tcant_ts <- full_join(
  tcant_S04 %>% mutate(reference = "Sabine et al. (2004)"),
  dcant_G19 %>% mutate(reference = "Sabine et al. (2004) + Gruber et al. (2019)"))

tcant_ts <- left_join(tcant_ts, co2_atm_reccap2)

# co2_atm_pi <- bind_cols(pCO2 = 280, dcant_mean = 0, year = 1800, dcant_sd = 0)
# 
# tcant_ts <- full_join(tcant_ts, co2_atm_pi)

tcant_ts <- tcant_ts %>% 
  arrange(year) %>% 
  mutate(tcant = cumsum(dcant_mean),
         tcant_sd = sqrt(dcant_sd^2 + lag(dcant_sd, default = 0)^2))

tcant_ts <- tcant_ts %>% 
  mutate(method = "Obs.~based~inventories",
         tcant_max = tcant + tcant_sd,
         tcant_min = tcant - tcant_sd) %>% 
  select(year, pCO2, reference, method, tcant, tcant_max, tcant_min)

```

### GCB models

```{r prepare_GCB}

Ocean_Sink <- Ocean_Sink %>% 
  group_by(year, type) %>% 
  summarise(GtC_mean = mean(GtC),
            GtC_sd = sd(GtC)) %>% 
  ungroup()


Ocean_Sink <- Ocean_Sink %>%
  filter(type == "models") %>%
  select(-type)

Ocean_Sink %>%
  ggplot(aes(
    year,
    GtC_mean,
    ymin = GtC_mean - GtC_sd,
    ymax = GtC_mean + GtC_sd
  )) +
  geom_ribbon(alpha = 0.3) +
  geom_path()

Ocean_Sink <- left_join(Ocean_Sink, co2_atm_reccap2)


Ocean_Sink %>%
  ggplot(aes(
    pCO2,
    GtC_mean,
    ymin = GtC_mean - GtC_sd,
    ymax = GtC_mean + GtC_sd
  )) +
  geom_ribbon(alpha = 0.3) +
  geom_path()


Ocean_Sink <- Ocean_Sink %>% 
  mutate(tcant_max = GtC_mean + GtC_sd,
         tcant_min = GtC_mean - GtC_sd,
         reference = "Friedlingstein et al. (2022)",
         method = "Ocean~biogeochemical~models~(GCB)") %>% 
  select(year, pCO2, reference, method, tcant = GtC_mean, tcant_max, tcant_min)

```

### Green function

```{r time_series, fig.asp=0.8}

khatiwala_m <- 
  khatiwala %>% 
  select(Year, ends_with("m"), -atm) %>% 
  pivot_longer(ends_with("m"),
               values_to = "m",
               names_to = "parameter") %>% 
  mutate(parameter = str_remove(parameter, "m"))

khatiwala_p <- 
  khatiwala %>% 
  select(Year, ends_with("p"), -atm) %>% 
  pivot_longer(ends_with("p"),
               values_to = "p",
               names_to = "parameter") %>% 
  mutate(parameter = str_remove(parameter, "p"))

khatiwala <- khatiwala %>% 
  select(Year, atm, ocean, fossil, landuse) %>% 
  pivot_longer(-Year,
               values_to = "value",
               names_to = "parameter")

khatiwala <- full_join(khatiwala, khatiwala_m) 
khatiwala <- full_join(khatiwala, khatiwala_p) 


khatiwala %>%
  filter(parameter == "ocean") %>% 
  group_split(parameter) %>%
  map(
    ~ ggplot(data = .x,
             aes(Year, value)) +
      geom_hline(yintercept = 0, linetype = 2) +
      geom_line() +
      labs(title = .x$parameter) +
      geom_ribbon(aes(ymin = m, ymax = p), alpha = 0.3)
  )


khatiwala_atm <- left_join(khatiwala %>% rename(year = Year),
                           co2_atm_reccap2)

khatiwala_atm <- khatiwala_atm %>%
  filter(parameter == "ocean") %>%
  select(-parameter)


khatiwala_atm <- khatiwala_atm %>%
  select(year, pCO2, tcant = value, tcant_max = p, tcant_min = m) %>% 
  mutate(reference = "Khatiwala et al. (2009)",
         method = "Ocean~inversion~(Green*\"'\"*s~\"function\")")

khatiwala_atm %>% 
  filter(year >= 1959) %>% 
  mutate(tcant = tcant - first(tcant),
         tcant_max = tcant_max - first(tcant_max),
         tcant_min = tcant_min - first(tcant_min)) %>% 
  tail(1)

12.7/87*1.17

```

## Plot

```{r khatiwala_vs_models}

tcant_1958 <- khatiwala_atm %>% 
  filter(year == 1958) %>% 
  pull(tcant)

Ocean_Sink <- Ocean_Sink %>% 
  mutate(tcant = tcant + tcant_1958,
         tcant_max = tcant_max + tcant_1958,
         tcant_min = tcant_min + tcant_1958)


tcant <- bind_rows(tcant_ts,
                   Ocean_Sink,
                   khatiwala_atm)

year_ticks <- c(seq(1800,1900,50),1920,1940,seq(1960,2010,10))

p <- tcant %>%
  filter(method == "none") %>%
  ggplot(
    aes(
      pCO2,
      tcant,
      ymin = tcant_min,
      ymax = tcant_max,
      col = method,
      shape = method,
      fill = method,
      linetype = method
    )
  ) +
  geom_path(data = tcant %>% filter(method %in% c("Ocean~biogeochemical~models~(GCB)", "Ocean~inversion~(Green*\"'\"*s~\"function\")"))) +
  geom_point(data = tcant %>% filter(method %in% c("Ocean~inversion~(Green*\"'\"*s~\"function\")"),
                                     year %in% year_ticks)) +
  geom_text(data = tcant %>% filter(method %in% c("Ocean~inversion~(Green*\"'\"*s~\"function\")"),
                                     year %in% year_ticks),
            aes(label = year),
            nudge_x = 5, nudge_y = -5) +
  geom_ribbon(
    data = tcant %>% filter(method %in% c("Ocean~biogeochemical~models~(GCB)", "Ocean~inversion~(Green*\"'\"*s~\"function\")")),
    alpha = 0.3,
    col = NA
  ) +
  geom_linerange(data = tcant %>% filter(method %in% c("Obs.~based~inventories"))) +
  geom_point(data = tcant %>% filter(method %in% c("Obs.~based~inventories"))) +
  scale_fill_manual(values = c("firebrick",  "steelblue", "black"),
                    labels = parse_format()) +
  scale_color_manual(values = c("firebrick",  "steelblue", "black"),
                     labels = parse_format()) +
  scale_shape_manual(values = c(19, 3, 3),
                     labels = parse_format()) +
  scale_linetype_manual(values = c(1, 1, 1),
                        labels = parse_format()) +
  guides(
    linetype = guide_legend(override.aes = list(linetype = c(1, 1, 1))),
    shape = guide_legend(override.aes = list(shape = c(19, NA, NA))),
    fill = guide_legend(override.aes = list(fill = c("NA",  "steelblue", "black")))
  ) +
  labs(x = expression(Atmospheric ~ pCO[2] ~ "[µatm]"),
       y = expression(C[ANT] ~ inventory ~ "[PgC]")) +
  theme_classic() +
  theme(
    legend.title = element_blank(),
    legend.position = c(0.7, 0.2),
    legend.background = element_rect(fill = "transparent"),
    legend.text.align = 0
  )

p

```


```{r redraw_plot}

g <- ggplotGrob(p)

## then we have to find out which child grob represents the legend
## the grob with the name "guide-box" is the one we are looking for
guide <- which(g$layout$name == "guide-box")

## the legend consists of guides and the background, go for the guides
guide_lines <- which(g$grobs[[guide]]$layout$name == "guides")

g$grobs[[guide]]$grobs[[guide_lines]]
## the guides contain a lot of different grobs
## if you look at g$grobs[[guide]]$grobs[[guide_lines]] you will see
## 4 segments representing the 4 lines, these are at position 4-5 and 7-8
## segments at 4 and 7 are the vertical lines and 5 and 8 the horizontal lines
## NOTE: this you have to find out "manually", if you change the order in your
##       ggplot the positions will be exactly switched
##       one could write e function which checks whether a line is horizontal
##       or vertical but this is most likely an overkill if this is for a 
##       single plot

## we can use gtable_filter to remove the unwanted lines
## it requires a regular expression formed by the names of the grobs to filter out
remove_pattern <- paste(g$grobs[[guide]]$grobs[[guide_lines]]$layout$name[c(4,15,22,6,13,20)],
    collapse = "|")

## write back the filtered gtable
g$grobs[[guide]]$grobs[[guide_lines]] <- 
   gtable_filter(g$grobs[[guide]]$grobs[[guide_lines]],
                 remove_pattern, 
                 invert = TRUE)


## draw the grid

grid.draw(g)


# 
# pdf(here::here("output/Fig1a.pdf"),
#     width = 7,
#     height = 5)
# print(grid.draw(g))
# dev.off()
# 
# jpeg(
#   here::here("output/Fig1a.jpg"),
#   width = 7,
#   height = 5,
#   units = "in",
#   res = 300,
#   quality = 100
# )
# print(grid.draw(g))
# dev.off()




```

```{r atm_co2_time_series_inlet}

tcant %>%
  filter(method %in% c("Ocean~inversion~(Green*\"'\"*s~\"function\")")) %>%
  ggplot() +
  geom_path(aes(year, pCO2)) +
  geom_path(aes(year, tcant))

beta <- 1.25
co2_atm_pi_value <- 275
tCant_col <- "forestgreen"


g_inset <-
  ggplot() +
  geom_line(data = tcant %>%
              distinct(year, pCO2),
            aes(year, (pCO2 - co2_atm_pi_value) * beta),
            col = tCant_col) +
  geom_path(data = tcant %>%
              filter(
                method %in% c("Ocean~inversion~(Green*\"'\"*s~\"function\")")
              ),
            aes(year, tcant)) +
  scale_y_continuous(name = expression(C[ANT] ~ inventory ~ "[PgC]"),
                     sec.axis = sec_axis(~ (. / beta + co2_atm_pi_value),
                                         name = expression(Atm. ~ pCO[2] ~ "[µatm]"),
                                         breaks = seq(280,420,40))) +
  scale_x_continuous(name = "Year", breaks = seq(1800, 2000, 50)) +
  scale_color_manual(values = "black") +
  theme_classic() +
  theme(
    axis.title.y.right = element_text(color = tCant_col),
    axis.text.y.right = element_text(color = tCant_col),
    axis.ticks.y.right = element_line(color = tCant_col),
    legend.background = element_rect(fill = "transparent"),
    plot.background = element_rect(fill = "transparent",
                                   color = "transparent"),
    legend.position = c(0.85, 0.2),
    legend.title = element_blank()
  )

g_inset

# combination of figures according to 
# https://cran.r-project.org/web/packages/ggplotify/vignettes/ggplotify.html

grid.draw(g)
vp = viewport(x=.35, y=.8, width=.45, height=.3)
pushViewport(vp)
grid.draw(ggplotGrob(g_inset))
upViewport()


pdf(here::here("output/Fig1a.pdf"),
    width = 7,
    height = 5)
grid.draw(g)
vp = viewport(x=.33, y=.8, width=.45, height=.35)
pushViewport(vp)
grid.draw(ggplotGrob(g_inset))
upViewport()
dev.off()

```


# beta

```{r prep_beta_analysis}

tcant_beta <- tcant %>% 
  select(year, pCO2, method, tcant)

tcant_beta_zero <- tcant_beta %>% 
  filter(year == min(year)) %>% 
  mutate(method = "Obs.~based~inventories")

tcant_beta <- bind_rows(
  tcant_beta,
  tcant_beta_zero
)

rm(tcant_beta_zero)

```


```{r beta_annual}


tcant_beta_annual <- tcant_beta %>% 
  group_by(method) %>% 
  arrange(year) %>% 
  mutate(delta_year = year - lag(year),
         `Delta*pCO2` = (pCO2 - lag(pCO2)) / delta_year,
         `Delta*tCant` = (tcant - lag(tcant)) / delta_year,
         beta = `Delta*tCant`/`Delta*pCO2`) %>% 
  ungroup() %>% 
  select(year, method, `Delta*pCO2`, `Delta*tCant`, beta)


tcant_beta_annual <- tcant_beta_annual %>% 
  pivot_longer(`Delta*pCO2`:beta,
               names_to = "parameter",
               values_to = "value")

tcant_beta_annual <- expand_grid(tcant_beta_annual, roll_mean_year = c(5,10,20,50)) 


tcant_beta_annual <- tcant_beta_annual %>%
  group_by(roll_mean_year, method, parameter) %>%
  arrange(year) %>%
  mutate(
    value_roll = rollmean(value, k = roll_mean_year, fill = NA)
  ) %>%
  ungroup()

tcant_beta_annual %>% 
  mutate(roll_mean_year = as.factor(roll_mean_year)) %>% 
  filter(year > 1959) %>% 
  ggplot() +
  geom_path(aes(year, value), col = "grey") +
  geom_point(aes(year, value), col = "grey") +
  geom_path(aes(year, value_roll, col = roll_mean_year)) +
  # coord_cartesian(ylim = c(0,3)) +
  theme(legend.position = "bottom") +
  scale_color_brewer(palette = "Dark2") +
  facet_grid(parameter ~ method, labeller = label_parsed)

ggsave(here::here("output/Fig1a_beta_1959.pdf"),
    width = 10,
    height = 7)


tcant_beta_annual %>% 
  mutate(roll_mean_year = as.factor(roll_mean_year)) %>% 
  ggplot() +
  geom_path(aes(year, value), col = "grey") +
  geom_point(aes(year, value), col = "grey") +
  geom_path(aes(year, value_roll, col = roll_mean_year)) +
  # coord_cartesian(ylim = c(0,3)) +
  theme(legend.position = "bottom") +
  scale_color_brewer(palette = "Dark2") +
  facet_grid(parameter ~ method, labeller = label_parsed, scales = "free_y")

ggsave(here::here("output/Fig1a_beta_1765.pdf"),
    width = 10,
    height = 7)

tcant_beta_annual %>% 
  mutate(roll_mean_year = as.factor(roll_mean_year)) %>% 
  ggplot() +
  geom_path(aes(year, value), col = "grey") +
  geom_point(aes(year, value), col = "grey") +
  geom_path(aes(year, value_roll, col = roll_mean_year)) +
  coord_cartesian(ylim = c(0,3)) +
  theme(legend.position = "bottom") +
  scale_color_brewer(palette = "Dark2") +
  facet_grid(parameter ~ method, labeller = label_parsed, scales = "free_y")

ggsave(here::here("output/Fig1a_beta_1765_yrange0-3.pdf"),
    width = 10,
    height = 7)

```

```{r beta_1959}


tcant_beta_period <- tcant_beta %>% 
  mutate(period = cut(year, c(1764, 1958, 2020)))

tcant_beta_period %>% 
  ggplot(aes(pCO2, tcant, color=method)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE,
              aes(linetype = period))
  
  
  
library(broom)

tcant_beta_period %>%
  group_by(period, method) %>%
  nest() %>%
  mutate(
    fit = map(.x = data,
              ~ lm(tcant ~ pCO2, data = .x)),
    tidied = map(fit, tidy),
    glanced = map(fit, glance)
  ) %>%
  select(-c(data, fit, glanced)) %>%
  unnest(tidied) %>% 
  filter(term == "pCO2")


```


```{r beta_1994_2007}


tcant_beta_period <- tcant_beta %>% 
  mutate(period = cut(year, c(1993, 2007)))

tcant_beta_period %>% 
  ggplot(aes(pCO2, tcant, color=method)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE,
              aes(linetype = period))
  
  
  
library(broom)

tcant_beta_period %>%
  group_by(period, method) %>%
  nest() %>%
  mutate(
    fit = map(.x = data,
              ~ lm(tcant ~ pCO2, data = .x)),
    tidied = map(fit, tidy),
    glanced = map(fit, glance)
  ) %>%
  select(-c(data, fit, glanced)) %>%
  unnest(tidied) %>% 
  filter(term == "pCO2")


```


```{r beta_1990_2020}


tcant_beta_period <- tcant_beta %>% 
  mutate(period = cut(year, c(1989, 2020)))

tcant_beta_period %>% 
  ggplot(aes(pCO2, tcant, color=method)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE,
              aes(linetype = period))
  
  
  
library(broom)

tcant_beta_period %>%
  group_by(period, method) %>%
  nest() %>%
  mutate(
    fit = map(.x = data,
              ~ lm(tcant ~ pCO2, data = .x)),
    tidied = map(fit, tidy),
    glanced = map(fit, glance)
  ) %>%
  select(-c(data, fit, glanced)) %>%
  unnest(tidied) %>% 
  filter(term == "pCO2")


```


## Write files

```{r write_time_series_files}

tcant <- tcant %>%
  mutate(
    method = str_replace_all(method, "~", " "),
    method = str_remove_all(method, "\""),
    method = str_remove_all(method, "\\*")
  ) %>%
  mutate(
    pCO2 = round(pCO2, 3),
    tcant = round(tcant, 3),
    tcant_min = round(tcant_min, 3),
    tcant_max = round(tcant_max, 3)
    )


tcant %>% 
  write_csv(here::here("output/Fig1a_data.csv"))


```






```{r time_series_delta, fig.asp=0.8, eval=FALSE}

khatiwala %>%
  pivot_longer(value:p,
               names_to = "estimate",
               values_to = "value") %>%
  arrange(Year) %>%
  group_by(parameter, estimate) %>%
  mutate(value_delta = value - lag(value)) %>%
  ungroup() %>%
  select(-value) %>%
  pivot_wider(names_from = estimate,
              values_from = value_delta) %>%
  rename(value_delta = value) %>% 
  group_split(parameter) %>%
  map(
    ~ ggplot(data = .x, aes(Year, value_delta)) +
      geom_hline(yintercept = 0, linetype = 2) +
      geom_line() +
      labs(title = .x$parameter) +
      geom_ribbon(aes(
        ymin = m, ymax = p), alpha = 0.3)
  )

```

